### ISSUE TITLE
ChatBot 대화명 추가

### ISSUE THREAD

**Issue by ghost** [kiheyunkim/SimpleChatBot#2]
- ### Bot 대화명 추가(ex. 챗봇, Bot, Chatbot 등 기본적인 이름 사용)
- ### 특정 명령어 입력 시 대화명 수정 기능 추가
    - #### 명령어 형식은 추후 html에 추가하거나 read me.md에 추가

**Comment by kiheyunkim** [comment]
대화명 수정 기능은 오버스펙으로 인해 보류
